# Generated by Django 3.0.3 on 2020-10-12 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_api', '0025_auto_20200902_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripecustomerinformation',
            name='plan_name',
            field=models.CharField(default='Kodiak Seat License', max_length=255),
        ),
        migrations.AddField(
            model_name='stripecustomerinformation',
            name='upcoming_invoice_subtotal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stripecustomerinformation',
            name='upcoming_invoice_total',
            field=models.IntegerField(default=0),
        ),
    ]
