# Generated by Django 3.0.3 on 2020-10-12 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_api', '0027_stripediscount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripediscount',
            name='amount_off',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stripediscount',
            name='duration_in_months',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stripediscount',
            name='percent_off',
            field=models.FloatField(null=True),
        ),
    ]
