# Generated by Django 3.0.3 on 2020-10-12 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_api", "0028_auto_20201012_0352"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stripecustomerinformation",
            old_name="customer_currency",
            new_name="_deprecated_customer_currency",
        ),
        migrations.RenameField(
            model_name="stripecustomerinformation",
            old_name="payment_method_card_brand",
            new_name="_deprecated_payment_method_card_brand",
        ),
        migrations.RenameField(
            model_name="stripecustomerinformation",
            old_name="payment_method_card_exp_month",
            new_name="_deprecated_payment_method_card_exp_month",
        ),
        migrations.RenameField(
            model_name="stripecustomerinformation",
            old_name="payment_method_card_exp_year",
            new_name="_deprecated_payment_method_card_exp_year",
        ),
        migrations.RenameField(
            model_name="stripecustomerinformation",
            old_name="payment_method_card_last4",
            new_name="_deprecated_payment_method_card_last4",
        ),
        migrations.RenameField(
            model_name="stripecustomerinformation",
            old_name="payment_method_id",
            new_name="_deprecated_payment_method_id",
        ),
        migrations.AlterField(
            model_name="stripecustomerinformation",
            name="_deprecated_customer_currency",
            field=models.CharField(
                db_column="customer_currency",
                help_text="Three-letter ISO code for the currency the customer can be charged in for recurring billing purposes.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="stripecustomerinformation",
            name="_deprecated_payment_method_card_brand",
            field=models.CharField(
                db_column="payment_method_card_brand",
                help_text="Card brand. Can be `amex`, `diners`, `discover`, `jcb`, `mastercard`, `unionpay`, `visa`, or `unknown`.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="stripecustomerinformation",
            name="_deprecated_payment_method_card_exp_month",
            field=models.CharField(
                db_column="payment_method_card_exp_month",
                help_text="Two-digit number representing the card’s expiration month.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="stripecustomerinformation",
            name="_deprecated_payment_method_card_exp_year",
            field=models.CharField(
                db_column="payment_method_card_exp_year",
                help_text="Four-digit number representing the card’s expiration year.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="stripecustomerinformation",
            name="_deprecated_payment_method_card_last4",
            field=models.CharField(
                db_column="payment_method_card_last4",
                help_text="The last four digits of the card.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="stripecustomerinformation",
            name="_deprecated_payment_method_id",
            field=models.CharField(
                db_column="payment_method_id",
                db_index=True,
                help_text="Unique identifier for Stripe PaymentMethod object.",
                max_length=255,
            ),
        ),
    ]
