# Generated by Django 3.0.3 on 2020-10-12 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_api", "0029_auto_20201012_1920"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stripecustomerinformation",
            name="plan_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="stripecustomerinformation",
            name="upcoming_invoice_subtotal",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="stripecustomerinformation",
            name="upcoming_invoice_total",
            field=models.IntegerField(),
        ),
    ]
